name: tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install ./

      - name: Test with pytest
        run: |
          pytest tests
